### PR TITLE
deps(automated): Update icons

### PR DESCRIPTION
**Pull request by thelukewalton**
Update icons 2024-10-24

### CODE REVIEW

**Comment by thelukewalton** [comment]
Update icons 2024-10-24

**Review by mikecoomber — APPROVED** [review]

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:06:31

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:17:04

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:21:25

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:24:50

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:27:21

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:30:05

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:34:09

**Comment by thelukewalton** [comment]
Update icons 24 Oct 2024, 19:39:17

**Pull request merged**
